# Generated by Django 5.0 on 2024-01-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("tag_map", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signature", models.CharField(max_length=255, unique=True)),
                (
                    "block_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("heading_block", "Heading"),
                            ("rich_text_block", "Rich Text"),
                            ("image_block", "Image"),
                            ("gallery_block", "Gallery"),
                            ("video_block", "Video"),
                            ("audio_block", "Audio"),
                            ("quote_block", "Quote"),
                            ("code_block", "Code"),
                            ("html_block", "HTML"),
                            ("markdown_block", "Markdown"),
                            ("embed_block", "Embed"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signature",
                "verbose_name_plural": "Signatures",
                "ordering": ["-signature"],
            },
        ),
        migrations.CreateModel(
            name="Sitemap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Sitemap",
                "verbose_name_plural": "Sitemaps",
            },
        ),
        migrations.CreateModel(
            name="Urls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("wp_id", models.IntegerField()),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("page_id", models.IntegerField(blank=True, null=True)),
                (
                    "sitemap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sitemap.sitemap",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
            },
        ),
    ]
