# Generated by Django 5.0 on 2023-12-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitemap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="tag_map",
            field=models.TextField(blank=True, null=True),
        ),
    ]
