# Generated by Django 5.0 on 2024-01-01 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sitemap", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Page",
            new_name="PageData",
        ),
        migrations.RenameModel(
            old_name="Urls",
            new_name="SitemapUrl",
        ),
        migrations.AlterModelOptions(
            name="pagedata",
            options={"verbose_name": "Page Data", "verbose_name_plural": "Pages Data"},
        ),
    ]
