# Generated by Django 5.0 on 2024-01-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitemap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signature", models.CharField(max_length=255, unique=True)),
                (
                    "block_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("heading_block", "Heading"),
                            ("rich_text_block", "Rich Text"),
                            ("image_block", "Image"),
                            ("gallery_block", "Gallery"),
                            ("video_block", "Video"),
                            ("audio_block", "Audio"),
                            ("quote_block", "Quote"),
                            ("code_block", "Code"),
                            ("html_block", "HTML"),
                            ("markdown_block", "Markdown"),
                            ("embed_block", "Embed"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
